version: '3.0'

services:
  node: &node
    container_name: rv-deliver-app-fullstack-node
    image: node:current-alpine3.14
    working_dir: "/opt/app"


  backend:
    <<: *node
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - "${PWD}/backend:/opt/app"
      - "${PWD}/backend/data.json:/opt/app/data.json"
    entrypoint: ["yarn", "start"]

  app:
    <<: *node
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "${PWD}/frontend:/opt/app"
    entrypoint: [ "yarn", "start" ]